name: Check pull request

on:
  pull_request:
    types: [ opened, reopened ]
    paths-ignore:
      - '*.md'

jobs:
  check:
    uses: ./.github/workflows/check.yml
    strategy:
      matrix:
        include:
          - name: "client"
            binary: "${{ github.event.repository.name }}"
            path: "./"
          - name: "server"
            binary: "${{ github.event.repository.name }}-server"
            path: "./${{ github.event.repository.name }}-server"
    with:
      name: ${{ matrix.name }}
      binary: ${{ matrix.binary }}
      path: ${{ matrix.path }}
